# fly.toml
app = "openchat-votre-nom"

[build]
  builtin = "Dockerfile"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  
  [[http_service.checks]]
    interval = "15s"
    timeout = "10s"
    method = "GET"
    path = "/"

[env]
  DEBUG = "false"
  PYTHONUNBUFFERED = "1"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024